name: Email Verification

on: [push, workflow_dispatch]

jobs:
  verify-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 24f2006360@ds.study.iitm.ac.in
        run: echo "Verification Complete"
